### ISSUE TITLE
External media support 

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#11]
Imgur.com

Redgifs.com

Catbox.moe (I think)

Gfycat.com 

And other popular hosting sites.

**Comment by test2a** [comment]
Viewing and downloading preferably

**Comment by SuhasDissa** [comment]
If you can show me an example reddit post with those external media ( no need for imgur ),
That would be very helpful

**Comment by test2a** [comment]
@SuhasDissa i.... can but that would mean including nsfw links and i am not sure i can do that here.


https://lemmy.ca/c/gifs

https://lemm.ee/post/567684

https://lemmy.ml/post/1966303

https://lemmy.ml/post/1231290

https://lemmy.ml/post/2160973

https://lemmy.ml/post/2138485

https://lemmy.ml/post/2642521

https://lemmyis.fun/post/22741



i hope these are good enough to make some sense of the variety of hosts and instances. i will be adding more varieties as i go.

**Comment by SuhasDissa** [comment]
Thank you for your efforts.
I think you didn't read my request correctly. I asked for "reddit posts".
I'm not being lazy here, Honestly I couldn't find any reddit posts with redgifs , catbox or gfycat to verify if my code is working correctly.

**Comment by SuhasDissa** [comment]
Oh, I didn't realize redgifs was a website with explicit content. It would have been helpful if you had mentioned that earlier.

**Comment by test2a** [comment]
@SuhasDissa no worries. i did write NSFW so... anyway, there is no hurry. these posts are for lemmy so supporting them would mean greater support there.

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [External media support](https://trello.com/c/fO5rI5Rw/4-external-media-support)
