### ISSUE TITLE
Link to original post

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#13]
Hi...

Checked 2.2 and it is much much better now. 

I felt something weird. I wanted to read comments on a post but couldn't. 

A link to go to the original post so that I can read or share that would be the next thing if you are willing. 

Rest, I am seeing 1-2 bugs which I will report regarding lemmy

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link to original post](https://trello.com/c/Tqa7YZk4/15-link-to-original-post)
