### ISSUE TITLE
lemmy community label wrong

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#15]
![Screenshot_20230809-165512](https://github.com/SuhasDissa/MemerizeApp/assets/39449563/78c04cfc-3dd5-464f-bb3c-8d57e4bdeb59)

the sidebar shows the correct icon but the label is wrong. it tries to show the icon but the placeholder is a textlabel so yeah, a small thing

**Comment by test2a** [comment]
oops #14 is already made so i will close this

**Comment by SuhasDissa** [comment]
Adding icon in the taskbar was not my intention. But I think that its a nice thing to have 🤔

**Comment by test2a** [comment]
@SuhasDissa yes. i suspect you did that but with the label, it fell apart. 

on the contrary, if the titlebar and "today, week, month" can be collapsed when user scrolls down, that would save space as opposed to the current fixed position
