### ISSUE TITLE
loop videos/gifs option

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#16]
at this point i am just spitballing papercut issues. :-) the app works now much better. 

the videos, say 10 seconds play once. the player does not restart. the slider has to be dragged back to start and then play to be pressed.

we could either have option to "keep autoplaying videos" 

or

turn play button into "restart" when it reaches the end.

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loop videos](https://trello.com/c/ibR9RoXj/7-loop-videos)
