### ISSUE TITLE
Internationalization 

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#18]
Can you start internationalization of the app so that it can be used in multiple languages? 

Weblate and others are easy options to do the same and because the text used is very little, this should be an easy exercise.

**Comment by SuhasDissa** [comment]
https://crowdin.com/project/memerize/

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Translations](https://trello.com/c/Yf1PkwU1/6-translations)
