### ISSUE TITLE
other sort options

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#20]
currently, the app only has "top" and then "today" as default but user can choose week or month as well but thats it.

https://gitlab.com/cosmosapps/stealth

this stealth app is the same thing but it is a more general reddit anonymous client but it also has these sort options.

new , controversial, top, rising, hot
![Screenshot_20230814-104809-134](https://github.com/SuhasDissa/MemerizeApp/assets/39449563/22aa3742-de90-4728-8a6b-77b2f5626990)

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Other sort options](https://trello.com/c/KzcK11Lf/10-other-sort-options)
