### ISSUE TITLE
Follow a user on reddit or lemmy

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#22]
We should be able to also follow users on both reddit and remmy. Currently we can only follow communities and subreddits

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Follow user on reddit](https://trello.com/c/Vq9sd3CX/14-follow-user-on-reddit)

**Comment by SuhasDissa** [comment]
I'm closing this issue as "Not planned" for now. I'll keep an eye on it and consider adding this feature if more people request it.
