### ISSUE TITLE
error loading online memes on maybemaybemaybe "day" option

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#28]
the default is "day" so maybemaybemaybe is not working for some reason. week and month sometimes work but only this subreddit i have seen this problem for the past few days
![Screenshot_20230822-221206](https://github.com/SuhasDissa/MemerizeApp/assets/39449563/28f697bb-f73e-4719-a3cc-e739623f9da7)

**Comment by SuhasDissa** [comment]
I'm not sure what's causing this error. I can't reproduce it at will, but I tried some general fixes that might solve it.
