### ISSUE TITLE
ProxiTok Support

### ISSUE THREAD

**Issue by ghost** [SuhasDissa/MemerizeApp#37]
I know it could be complicated so I ask you not to pay too much attention to this request and close it just in case, 

but we can have the addition of the fronted Proxitok for Tiktok Meme content?

Maybe like Reddit or Lemmy, where you can subscribe to certain subreddits and communities, you could do the same thing for Tiktok Profiles with Proxitok (ツ)

**Comment by SuhasDissa** [comment]
Thanks for the suggestion.
I will look into it.

**Comment by SuhasDissa** [comment]
I've been working on adding ProxiTok support, but I haven't been able to find any official or unofficial APIs to access it.
The only way to get data from ProxiTok right now is to scrape their website, which I'm not comfortable with doing.

I'm still looking into other options, but I wanted to let you know where things are going.
