### ISSUE TITLE
Allow subscribing to multi reddits

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#4]

**Comment by SuhasDissa** [comment]
I added this feature and its working perfectly fine.
However I'm not sure if its what you asked for.

https://github.com/SuhasDissa/MemerizeApp/assets/64766434/83c8f768-d22f-434b-96c7-150e47bc216b

**Comment by test2a** [comment]
@suhasdissa ah. You... Didn't get me 

https://www.howtogeek.com/670169/how-to-create-multireddits-to-combine-multiple-subreddits/

**Comment by test2a** [comment]
@SuhasDissa 

https://www.reddit.com/r/multihub/

this one has a list of multi-reddits. if we can support these, like the gardening one, that is what i mean by a "multi-reddit" because you dont subscribe to each one separately but together combined

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multi Reddit support](https://trello.com/c/9Bnz1RHa/11-multi-reddit-support)
