### ISSUE TITLE
Support Lemmy and kbin

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#5]
Don't know if its possible but supporting Lemmy and kbin would be such an awesome thing to supoort the communities there.

**Comment by SuhasDissa** [comment]
I haven't used lemmy or kbin before. If you can give me a short list of your favorite meme communities, that would be very helpful.
I'm hoping to include some of them in my app out of the box.

**Comment by test2a** [comment]
https://browse.feddit.de/ this is a lemmy communities search engine.  you can find most communities there.



https://lemmy.ml/c/memes

https://lemmy.world/c/mildlyinfuriating

just to point out a few.


my point is, if you can support lemmy/kbin, users will use their own communities.

**Comment by SuhasDissa** [comment]
By the way does lemmy work similar to mastodon?

Is it possible to access all communities through one lemmy instance?

**Comment by test2a** [comment]
yeah https://github.com/thunder-app/thunder

try this...

look at browse.feddit.de


what it does is, like mastodon search, you paste the url of a lemmy instance in your search and it opens the same which you can follow. 

the same would apply to memerize. 

you paste url to a lemmy or kbin instance and ht subscribe.

**Comment by SuhasDissa** [comment]
Thanks. I will add that feature.

**Comment by test2a** [comment]
@SuhasDissa sure. thanks.

just a note, there are 2 methods of identifying a lemmy community.

!memes@lemmy.ml a URI 

and 

https://lemmy.ml/c/memes

a user can use both

**Comment by SuhasDissa** [comment]
I was able to add Lemmy support successfully.
I'll add Kbin support later.
