### ISSUE TITLE
Onscreen audio control

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#6]
It appears the audio is on by default for all videos. 

There should be an onscreen control to play or stop audio. 

Like other reddit apps, the audio control should have the following functions. 

Off or on by default 
Changing state should be either per video or by default. 

I personally like to have a mix of both so an option would be nice. 

What I mean is, I start the app, audio is playing for example. The audio button shows meaning this video has audio. I click it. The next video I open, it can either have the audio on because I left audio on in precious video or the state would reset to default. 

As I said, an option would be nice.

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mute videos](https://trello.com/c/YLEVaaRh/8-mute-videos)
