### ISSUE TITLE
photo viewer bug?

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#7]
![Screenshot_20230803-163004](https://github.com/SuhasDissa/MemerizeApp/assets/39449563/c6aa31ce-b9f0-4381-8331-7766cf06636a)

i dont know if you've noticed but the photo viewer allows photos to be placed anywhere on the screen, not a good way to navigate the screen because the only way out is to go back which can take you to 2  backs and leave the current position. 

other apps, like any reddit app or other photo viewers do not allow photos to be placed like this.... this feels weird i suppose.

**Comment by SuhasDissa** [comment]
Its not a bug. It's there to let users freely zoom and pan the meme. Sometimes its very helpful to read small text.

I never had any problem with 
Anyway, I'll remove that feature if its that annoying.

**Comment by test2a** [comment]
@SuhasDissa i understand that.... can you see infinity for reddit or stealth ? they too allow zoom and pan but dont allow the exact behaviour of this app... they let you zoom and move around but not pan the image so the image remains on screen at all times....

https://github.com/SuhasDissa/MemerizeApp/assets/39449563/429d1144-5efd-41d0-810c-dbd06f922400


here.... infinity screenrecording.
