### ISSUE TITLE
Kbin Support

### ISSUE THREAD

**Issue by SuhasDissa** [SuhasDissa/MemerizeApp#8]
I'll add Kbin support later.

_Originally posted by @SuhasDissa in https://github.com/SuhasDissa/MemerizeApp/issues/5#issuecomment-1665129388_

**Comment by test2a** [comment]
https://kbin.social/m/Funny

@Funny@kbin.social 


https://kbin.social/m/memes

@memes@kbin.social 

just a few examples

**Comment by SuhasDissa** [comment]
Kbin API seems to be broken at the moment. I have to postpone implementing this feature.

**Comment by test2a** [comment]
@SuhasDissa no worries. the app is already so much better.

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kbin support](https://trello.com/c/E8qRJgYL/9-kbin-support)
