### ISSUE TITLE
set size limit on cache or disable cache or auto clear cache

### ISSUE THREAD

**Issue by test2a** [SuhasDissa/MemerizeApp#9]
i've already been using the app for a few days and my cache has reached 265MB. 

would it be possible to 

1. set max cache size (slider, or say 100MB)
2. disable cache
3. auto clear cache (7 days for example)
4.  per subreddit/communtity/magazine cache setting

these settings are important for such a image/video centric app so as to not balloon.  4 is maybe too advanced so if it needs to go into a new issue, that would be okay

**Comment by test2a** [comment]
@SuhasDissa how about the auto clear cache based on a set limit? i am not saying "limit the cache to 100MB" but "trigger clear cache if it reaches 100MB. how does that sound?

**Comment by SuhasDissa** [comment]
I went with the option 1. Added a cache limit option only for images. I guess its better than nothing.

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image Cache](https://trello.com/c/UHT7lFUo/5-image-cache)
